travis:
  secure:
    BINSTAR_TOKEN: SXR8nkf2SRfx266RYDsV1IW/kpN7rX6UIQYYmmYpmemUMlT5sBwrCmKyxnMi1DtoajHs85eyVkhryGAdbIAHEBeUPJmdLbNicrYJd9I433pPYK2BPE6Uvz7cm33hamILshSz2RQyZ+9eFgUyYfcgzf+1P/UawxDUbhWzu7mKg7vpaTHr9a4HlEaiukv4angHshZL3KNyx0cZ6Vdoh00ndpD9BnYmENPlcEPMGgBSAh0dEw3gLDq+bXA/VOywMofzqIUlvwNRXqlFaH6nP2k2At1HySPDo/0hWjL9u3QFfquBP3ny0ufG/p+Es8p6T3XvnPB0u55+Bld5EQo1T6yS6PeIb89CKkrM+xLBV/QxXAl32GqWSRGG6WpGOM1vF0fu/Ph6jGZt2y6jmMZXn91mDZO/kvRKfR/hVKa8fB2t6BQ/PwxyuaWfcp/C9OU6csj03efKrCYN2soz1tbX6AW5iWBGA/j6Q3sB4Oo49UOZSQq1kQjKhk83C4kPH4+uhx+uSYDZSfA7uJaQHE6wBS9D6o3yDVVyHvrhfksxd1dUqRDUQJriSoTTv4Xgu5mCQP+15+U8QbXWq6nZGOCuMoF9ukC8Wf33XBLRkB788U9OdsWIaseTsIasG9gPsg58BFG+LXamqgV7L1BBTXjJf+B9aQxS08ppNNlMrbQ9oZSJxdk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
